# Site settings
title: incoherent essays
email: david@dfoxx.com
description: > # this means to ignore newlines until "baseurl:"
  if you don't know, now you know...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dfoxx.github.io" # the base hostname & protocol for your site

# Build settings
timezone: America/New_York
markdown: kramdown
